### ISSUE TITLE
点击获取令牌会百分百报错闪退

### ISSUE THREAD

**Issue by fuguiKz** [funnyzak/react-native-v2ex#82]
com.facebook.react.common.JavascriptException: TypeError: Object is not a constructor (evaluating 'new(r(d[4]).WebView)({})')

This error is located at:
    in u
    in Unknown
    in Unknown
    in Unknown
    in RCTView
    in Unknown
    in f
    in RNSScreen
    in A
    in Unknown
    in D
    in E
    in v
    in RNSScreenStack
    in ScreenStack
    in h
    in RCTView
    in Unknown
    in y
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in Unknown
    in c
    in RNCSafeAreaProvider
    in Unknown
    in Unknown
    in l
    in l
    in u
    in l
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in b, stack:
u@1744:815
Er@55:43096
da@55:93007
ii@55:84241
li@55:84143
ri@55:83908
Ka@55:80841
Ka@-1
dt@55:27269
Pe@55:96228
Ce@55:14121
Le@55:14498
receiveTouches@55:15297
value@36:3556
<unknown>@36:673
value@36:2503
value@36:645
value@-1

	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:7)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:18)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:13)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:1)
	at android.os.Looper.loop(Looper.java:236)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:8)
	at java.lang.Thread.run(Thread.java:923)

**Comment by fuguiKz** [comment]
实际上点击任何跳转浏览器的操作都会报错，机型miui ，安卓11

**Comment by funnyzak** [comment]
@fuguiKz 是Weblink组件bug，已调整更新。再拉取或安装最新看看。
